using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PERI.ListExtender
{
    /// <summary>
    /// 
    /// </summary>
    public class PdfLayout
    {
        /// <summary>
        /// List of Headers that will be generated by order
        /// </summary>
        public List<PdfHeader> Headers { get; set; } = new List<PdfHeader>();

        /// <summary>
        /// List of Footers that will be generated by order
        /// </summary>
        public List<PdfFooter> Footers { get; set; } = new List<PdfFooter>();

        /// <summary>
        /// The document will be generated in landscape by default
        /// </summary>
        public bool IsLandscape { get; set; } = false;

        /// <summary>
        /// The size of the font
        /// </summary>
        public int FontSize { get; set; } = 8;
    }
        
    public class PdfHeader
    {
        public string Text { get; set; }
        public int FontSize { get; set; } = 9;
        public int Alignment { get; set; } = PdfPCell.ALIGN_CENTER;
    }
        
    public class PdfFooter
    {
        public string Text { get; set; }
        public int FontSize { get; set; } = 6;
        public int Alignment { get; set; } = PdfPCell.ALIGN_CENTER;
    }
}